name: run test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Ensure Go modules are tidy
        run: |
          go mod tidy
          go mod vendor
          git diff --exit-code .

      - name: Run tests
        run: make test
